stages:
  - jar-build
  - docker-build
before_script:
  - aliimagegateway=registry.docker.quancheng-ec.com:5000/saluki-example-client:V1.5.3-`TZ=CST-8 date '+%Y%m%d'` 
  - aliimagemonitor=registry.docker.quancheng-ec.com:5000/saluki-monitor:V1.5.3-`TZ=CST-8 date '+%Y%m%d'`
  - hostname -i
  - whoami
  
build_jar:
  stage: jar-build
  script:
    - mvn clean install -U -Dmaven.test.skip=true
    - mvn deploy
  only:
    - develop
    
build_images:
   stage: docker-build
   script:
    - echo `git rev-parse --short HEAD` >> saluki-monitor/saluki-monitor-console/bin/git.tag
    - echo $image
    - if [ "`docker images | awk '/^registry.docker.quancheng-ec.com:5000/ { print $3 }'`" ]; then docker rmi -f $(docker images | awk '/^registry.docker.quancheng-ec.com:5000/ { print $3 }' ); fi
    - docker build --no-cache -t $aliimagemonitor -f saluki-monitor/saluki-monitor-console/Dockerfile .
    - echo "Push Image:" $aliimagemonitor " to repository..."
    - docker push $aliimagemonitor
    - docker build --no-cache -t $aliimagegateway -f saluki-gateway/Dockerfile .
    - echo "Push Image:" $aliimagegateway " to repository..."
    - docker push $aliimagegateway
   only:
    - develop