stages:
  - jar-build
  - docker-build
before_script:
  - aliimageclient=nexus.quancheng-ec.com:5000/saluki-example-client:`TZ=CST-8 date '+%Y%m%d'` 
  - aliimageserver=nexus.quancheng-ec.com:5000/saluki-example-server:`TZ=CST-8 date '+%Y%m%d'`
  - aliimagemonitorprod=nexus.quancheng-ec.com:5000/saluki-monitor-web-local:`TZ=CST-8 date '+%Y%m%d'`
  - aliimagemonitordev=nexus.quancheng-ec.com:5000/saluki-monitor-web-prod:`TZ=CST-8 date '+%Y%m%d'`
  - aliimagemonitorlocal=nexus.quancheng-ec.com:5000/saluki-monitor-web-dev:`TZ=CST-8 date '+%Y%m%d'`
  - hostname -i
  - whoami
build_jar:
  stage: jar-build
  script:
    - gradle clean uploadArchives --refresh-dependencies
  only:
    - develop

build_images:
   stage: docker-build

   script:
    - echo $image
    - if [ "`docker images | awk '/^nexus.quancheng-ec.com:5000/ { print $3 }'`" ]; then docker rmi -f $(docker images | awk '/^nexus.quancheng-ec.com:5000/ { print $3 }' ); fi
    - gradle clean build --refresh-dependencies
    - echo "Build Docker Image..."
    - docker build --no-cache -t $aliimageclient -f saluki-example/saluki-example-client/Dockerfile .
    - echo "Push Image:" $aliimageclient " to repository..."
    - docker push $aliimageclient
    - docker build --no-cache -t $aliimageserver -f saluki-example/saluki-example-server/Dockerfile .
    - echo "Push Image:" $aliimageserver " to repository..."
    - docker push $aliimageserver
    - docker build --no-cache -t $aliimagemonitorprod -f saluki-monitor/saluki-monitor-web/Dockerfile-prod .
    - echo "Push Image:" $aliimagemonitorprod " to repository..."
    - docker push $aliimagemonitorprod
    - docker build --no-cache -t $aliimagemonitordev -f saluki-monitor/saluki-monitor-web/Dockerfile-dev .
    - echo "Push Image:" $aliimagemonitordev " to repository..."
    - docker push $aliimagemonitordev
    - docker build --no-cache -t $aliimagemonitorlocal -f saluki-monitor/saluki-monitor-web/Dockerfile-local .
    - echo "Push Image:" $aliimagemonitorlocal " to repository..."
    - docker push $aliimagemonitorlocal

   only:
    - develop