stages:
  - jar-build
before_script:
  - aliimageclient=nexus.quancheng-ec.com:5000/saluki-example-client:`TZ=CST-8 date '+%Y%m%d'` 
  - aliimageserver=nexus.quancheng-ec.com:5000/saluki-example-server:`TZ=CST-8 date '+%Y%m%d'`
  - aliimagemonitor=nexus.quancheng-ec.com:5000/saluki-monitor:`TZ=CST-8 date '+%Y%m%d'`
  - hostname -i
  - whoami
build_jar:
  stage: jar-build
  script:
    - gradle clean uploadArchives --refresh-dependencies
    - cd saluki-plugin/saluki-maven-plugin
    - mvn clean install
    - mvn deploy
  only:
    - V1.5.2