notifications:
  email:
    recipients:
      - 297442500@qq.com
  on_success: change
  on_failure: always

language: java

matrix:
  include:
  # On OSX, run with default JDK only.
  # - os: osx
  # On Linux, run with specific JDKs only.
  - os: linux
    env: CUSTOM_JDK="oraclejdk8"
  - os: linux
    env: CUSTOM_JDK="oraclejdk7"
  - os: linux
    env: CUSTOM_JDK="openjdk7"

before_install:
  - echo 'MAVEN_OPTS="$MAVEN_OPTS -Xmx1024m -XX:MaxPermSize=512m -XX:+BytecodeVerificationLocal"' >> ~/.mavenrc
  - cat ~/.mavenrc
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then jdk_switcher use "$CUSTOM_JDK"; fi


script:
  - mvn clean install -U -Dmaven.test.skip=true

 