spring:
  application:
    name: example-client
server:
  port: 8080
saluki:
  grpc:
    registryAddress: localhost:8500
    group: example
    version: 1.0.0
    host: 127.0.0.1
    realityRpcPort: 12201