spring:
  profiles:
    active: dev
  application:
    name: example-client
server:
  port: 9000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
saluki:
  grpc:
    registryAddress: localhost:8500